#index:
#    path: /
#    controller: App\Controller\DefaultController::index

places:
    type:     rest
    resource: App\Controller\PlaceController

users:
    type:     rest
    resource: App\Controller\UserController

prices:
    type:     rest
    resource: App\Controller\PriceController

app.swagger_ui:
    path: /api/doc/{area}
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui, area: default }
app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }
